pages:
  image: node:12
  stage: deploy
  variables:
    NODE_ENV: production
  script:
    - npm ci
    - mkdir public
    - mv app.js index.html controllers css gui partials services templates node_modules public/
  artifacts:
    paths:
      - public
  only:
    - master
